export const universitylist = [
    {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
            {
                speciality: "Women's confect",
                domain: "Arts, culture, design, fashion",
                duration: "2",
                type_diploma: "Technical",
                graduates: "303"
            },
            {
                speciality: "Women's confect",
                domain: "Arts, culture, design, fashion",
                duration: "2",
                type_diploma: "Technical",
                graduates: "303"
            }
        ]
    },
    {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
        ],
      },
      {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
        ],
      },
      {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
        ],
      },
      {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
        ],
      },
      {
        logo: "https://www.jobpaw.com/private/logoetablissement/418.png",
        name: "Bee Homemaking School",
        link:"bee-homemaking-school",
        type_training: "Technical",
        phone: "2257 7260",
        address: "Rue C. Mayard # 207, Pétion-Ville, Port-au-Prince, West",
        acronym: "-",
        website: "www.beehomamakingschool.com",
        country: "Haiti",
        fax: "999 00976 54",
        email: "info@bee.com",
        description: "Diploma in Cooking, Pastry, Women's Confectionery Cutter",
        training_program: [
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
          {
            speciality: "Women's confect",
            domain: "Arts, culture, design, fashion",
            duration: "2",
            type_diploma: "Technical",
            graduates: "303",
          },
        ],
      },
    // Additional university objects...
];